apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgAJHB5UKvTfmpYNv+o9xvs0R4dqpQqofPOSgVqEUMY748Ms8IUPD+JBPjnQrUw58Ei6dKcULW36AIb/+8vCV8riaK0yaFQY4OnsqFhM9k+rjVHCMXhRdCj4RWu8nz4nW69Bon5L1uQkKkurtSArUd8bpYFSNvrroe3Nv8voGt+f84Kv/xYXG3cfzsXBeg+WY4eNmNnDW7lTNVmWTcAwTqF4Fqwe18Xd7ixOe55GQDSsvlAp8g+yXC9l4D/KFzCZ761NLrYhnKqoncZo5JY0a2qGDuoCSXeVjcOw0RyP/gUyo2mIQ4S270pQ/RrJGAJfq2n2xCZrxp6vKCt9VDRsHlGNCpcrTIXDROY4SyvCJBj/PG+UFIdTgS8jQfYFGybwTGRTrYtUILQRV0Ca68/viS9XKqKD1FnLHtL177Cp5kphlzZVTRazGQ1ZtTANug1gdwlM0LzsouMzaTzu8jQuENaTV4Lmj1pQXLJFFGcGrFER6JQ3MYVSjac7vIzLkC80bKCzBN1GcqHGveJGfMVSu353fuYAvXiwR5XprPsqwaoZhog1rMhTA4L3FedqRIFVnelhrP6wVBeMWlF5Qs7kDi/LWJp+xr9ITc5ip2u1NnfbgWkBCVdUZv9KRYTglsTVEQLKES136UWtjhXkvXeBoJp+pWZGqZtcYzWgsEdJKMchG12aRr/8gc0+zFu8gfGVYWF+050=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: dev-demo
